# Default locale for UI strings
locale: "fr"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # mail-body-default:    "Here is my feedback:\n"
  # redo:                 "Redo"
  # ok:                   "Okay"
  contact-intro:        "Vos remarques : "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "Test del algoritmo de autoevaluación de COVID-19"
 logo:     "https://assets.change.org/photos/8/yv/vj/cwYVVJHPucsSJDI-800x450-noPad.jpg?1536100710https://solidarites-sante.gouv.fr/IMG/siteon0.jpg"
 color:    "is-primary"
 subtitle: "Este sitio tiene documentación para la implementación del algoritmo de orientación de COVID-19."

# Website footer
footer:
 text:    "Demostración del algortimo de orientación de COVID-19."
 contact:  "reference_email_here@salud.gob.ar"

# Allow users to send you emails with the summary?
mail-to: "reference_email_here@salud.gob.ar"

# Display help along with questions by default?
display-help: true

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
display-score-details: true

# Only the score with the highest value?
display-score-top-result: true

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-outputs?
conditional-navigation: false

# Some text message to always display after the score results
display-unconditionally: "Quédese en su casa el máximo tiempo posible hasta que los síntomas mejoren. Tome su temperatura dos a tres veces por día. Siga todas las medidas de higiene."

# Set initial variables to register scores.  Each entry of
# score-variables start with the name of the variable (you can pick
# up any yaml-acceptable name), then:
#
# (1) "display": what to display when detailed scores are displayed
# (2) "value": the initial value of the variable
# (3) "as-top-result-display": what to display when the variable is
#      the one with the highest score when the user is done.
score-variables:
  moins-de-15-ans:
    display: "Menos de 15 años"
    value: 0
  plus-de-50-ans:
    display: "Más de 49 años"
    value: 0
  poids:
    display: "Peso (kgs)"
    value: 0
  taille:
    display: "Talla (mètres)"
    value: 0
  fievre:
    display: "Fiebre"
    value: 0
  toux:
    display: "Tos"
    value: 0
  anosmie:
    display: "Problemas con el gusto/olfato"
    value: 0
  douleurs:
    display: "Dolor"
    value: 0
  diarrhees:
    display: "Diarrea"
    value: 0
  facteurs-gravite-mineurs:
    display: "Factores de gravedad menores"
    value: 0
  facteurs-gravite-majeurs:
    display: "Factores de gravedad mayores"
    value: 0
  facteurs-pronostiques:
    display: "Factores pronósticos"
    value: 0

# Sync with pseudo-code.org:
# Priority 1 -> FIN1
# Priority 6 -> FIN2
# Priority 4 -> FIN3
# Priority 3 -> FIN4
# Priority 2 -> FIN5
# Priority 5 -> FIN6
# Priority 8 -> FIN7
# Priority 7 -> FIN8
# Priority 9 -> FIN9
#
# Set conditional output depending on scores.
# Each entry is composed of the name of the condition (you can pick up
# any yaml-acceptable name), then:
#
# (1) notification (optional): bulma-based class names for the UI notification
# (2) message (mandatory): message to display when one of the condition is met
# (3) anything else is a "condition", which lists variables and their minimal
# values for the condition to be met.
conditional-score-outputs:
  FIN1:
    priority: 1
    node: "fin-moins-de-15-ans"
    message: "contacte a su médico tratante si tiene dudas. Esta aplicación no está adaptada para personas de menos de 15 años. En caso de urgencia llame al 15 [15](tel:15)."
    notification: "is-danger"
    condition-1:
      moins-de-15-ans: 1
  FIN5:
    priority: 2
    node: "fin"
    message: "Llame al [15](tel:15)."
    notification: "is-danger"
    condition-1:
      fievre: 1
      facteurs-gravite-majeurs: 1
  FIN4:
    priority: 3
    message: "Teleconsulta o médico general o visita domiciliaria (SOS).<br/>si no es posible llame al [15](tel:15)."
    notification: "is-danger"
    condition-1:
      facteurs-gravite-mineurs: 2
      facteurs-pronostiques: 1
      fievre: 1
    condition-2:
      facteurs-gravite-mineurs: 2
      facteurs-pronostiques: 1
      diarrhees: 1
    condition-3:
      facteurs-gravite-mineurs: 2
      facteurs-pronostiques: 1
      toux: 1
      douleurs: 1
    condition-4:
      facteurs-gravite-mineurs: 2
      facteurs-pronostiques: 1
      toux: 1
      anosmie: 1
  FIN3:
    priority: 4
    notification: "is-warning"
    message: "Teleconsulta o médico general o visita domiciliaria (SOS).<br/>Ante la menor duda, llame al [15](tel:15)."
    condition-1:
      toux: 1
      douleurs: 0
      fievre: 0
      anosmie: 0
      facteurs-gravite-mineurs: 1
    condition-2:
      douleurs: 1
      toux: 0
      anosmie: 0
      fievre: 0
      facteurs-gravite-mineurs: 1
    condition-3:
      anosmie: 1
      douleurs: 0
      toux: 0
      fievre: 0
      facteurs-gravite-mineurs: 1
    condition-4:
      toux: 1
      anosmie: 0
      douleurs: 0
      fievre: 0
      facteurs-pronostiques: 1
    condition-5:
      toux: 0
      anosmie: 0
      douleurs: 1
      fievre: 0
      facteurs-pronostiques: 1
    condition-6:
      anosmie: 1
      toux: 0
      douleurs: 0
      fievre: 0
      facteurs-pronostiques: 1
  FIN7:
    priority: 8
    notification: "is-info"
    message: "Su situación no se debe probablemente a COVID-19. <br/>Consulte a su médico tratante si tiene alguna duda.<br/>Si nuevos síntomas aparecieran, rehaga este test."
    condition-1:
      toux: 1
      anosmie: 0
      douleurs: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
    condition-2:
      douleurs: 1
      toux: 0
      anosmie: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
    condition-3:
      anosmie: 1
      toux: 0
      douleurs: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
  FIN9:
    priority: 9
    notification: "is-success"
    message: "Su situación no se debe probablemente a COVID-19. No dude en contactar a su médico tratante ante cualquier duda.<br/>Ud. puede hacer el test ante nuevos síntomas para reevaluar su situación.<br/>Para toda información concerniente a COVID-19, llame al 0 800 130 000."
    condition-1:
      toux: 0
      fievre: 0
      douleurs: 0
      anosmie: 0

# Mandatory configuration option
# FIXME: complete documentation
tree:
  - node:       "0"
    text:       "COVID-19: Algoritmo de orientación - sitio de demostración"
    home-page:  true
    force-help: true
    help:       "Este sitio es una demostración para el algoritmo de orientación de COVID-19. Ningún dato es recolectado"
    choices:
    - answer: "Empezar"
      goto:   "1.1"
      color:  "is-info"

  - node:       "1.1"
    progress:   "[1 23]"
    text:       "Piensa Ud. haber tenido fiebre los últimos días (escalofríos, sudoración)?"
    start-page: true
    choices:
    - answer:  "Si"
      score:
        fievre:
          value: 1
      goto:    "1.1.1"
      color:   "is-info"
    - answer:  "No"
      color:   "is-info"
      goto:    "1.2"
    - answer:  "No sabe"
      color:   "is-info"
      goto:    "1.2"
      score:
        fievre:
          value: 1

  - node:       "1.1.1"
    progress:   "[2 23]"
    text:       "Cuál es su temperatura?"
    choices:
    - answer:  "**Inferior** o igual a 35,4°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "Entre 35,5 y 37,7°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "Entre 37,8 y 38,9°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "**Superior** o igual à 39°C"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-info"
    - answer:  "No se"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-info"

  - node:    "1.2"
    progress:   "[3 23]"
    text:    "Tiene Ud. tos o un aumento de su tos habitual los últimos días?"
    choices:
    - answer:  "Si"
      score:
        toux:
          value: 1
      goto:    "1.3"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.3"
      color:   "is-info"

  - node:      "1.3"
    progress:   "[4 23]"
    text:      "Tiene Ud. una fuerte disminución de su gusto o de su olfato los últimos días?"
    choices:
    - answer:  "Si"
      goto:    "1.4"
      color:   "is-info"
      score:
        anosmie:
          value: 1
    - answer:  "No"
      goto:    "1.4"
      color:   "is-info"

  - node:    "1.4"
    progress:   "[5 23]"
    text:    "Tiene Ud. dolor de garganta que haya aparecido los últimos días?"
    choices:
    - answer:  "Si"
      score:
        douleurs:
          value: 1
      goto:    "1.5"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.5"
      color:   "is-info"

  - node:    "1.5"
    progress:   "[6 23]"
    text:    "Ha tenido Ud. diarrea las últimas 24 hs (al menos 3 deposiciones diarias)?"
    choices:
    - answer:  "Si"
      score:
        diarrhees:
          value: 1
      goto:    "1.6"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.6"
      color:   "is-info"

  - node:    "1.6"
    progress:   "[7 23]"
    text:    "Tiene Ud. más fatiga de la habitual estos días?"
    choices:
    - answer:  "Si"
      goto:    "1.6.1"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.7"
      color:   "is-info"

  - node:    "1.6.1"
    progress:   "[8 23]"
    text:    "Esta fatiga lo obliga a estar en reposo la mayor parte del día?"
    choices:
    - answer:  "Si"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.7"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.7"
      color:   "is-info"

  - node:    "1.7"
    progress:   "[9 23]"
    text:    " Ha estado Ud. imposibilitado de alimentarse o de beber las últimas 24 horas o más?"
    choices:
    - answer:  "Si"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:
        conditional-score-outputs: true
        default: "1.8"
      color:   "is-info"
    - answer:  "No"
      goto:    "1.8"
      color:   "is-info"

  - node:    "1.8"
    progress:   "[10 23]"
    text:    "En las últimas 24 horas, ha notado Ud. falta de aire no habitual. En las últimas 24 horas, ha notado una falta de aliento INUSUAL al hablar o hacer esfuerzos leves?"
    choices:
    - answer:  "Si"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:
        conditional-score-outputs: true
        default: "2.1"
      color:   "is-info"
    - answer:  "No"
      goto:    "2.1"
      color:   "is-info"

  - node:    "2.1"
    progress:   "[11 23]"
    text:    "Cuál es su edad?"
    choices:
    - answer:  "Menos de 15 años"
      goto:
        conditional-score-outputs: true
        default: "2.2"
      score:
        moins-de-15-ans:
          value: 1
      color:   "is-info"
    - answer:  "Entre 15 y 49 años"
      goto:    "2.2"
      color:   "is-info"
    - answer:  "Entre 50 et 69 años"
      score:
        plus-de-50-ans:
          value: 1
      goto:    "2.2"
      color:   "is-info"
    - answer:  "70 años o más"
      goto:    "2.2"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
        plus-de-50-ans:
          value: 1

  - node:    "2.2"
    progress:   "[12 23]"
    text:    "Cuál es su peso en kilogramos?"
    help: "**Note aux développeurs:** demandez la saisie du poids exact."
    choices:
    - answer:  "<60"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 60
    - answer:  "60-70"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 70
    - answer:  "70-80"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 80
    - answer:  "80-90"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 90
    - answer:  "90-100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 100
    - answer:  ">100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 110

  - node:    "2.3"
    progress:   "[13 23]"
    text:    "Cuál es su altura en metros?"
    help: "**Note aux développeurs:** demandez la saisie de la taille exacte."
    choices:
    - answer:  "<1m50"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.40
    - answer:  "1m50-1m60"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.50
    - answer:  "1m60-1m70"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.60
    - answer:  "1m70-1m80"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.70
    - answer:  "1m80-1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.80
    - answer:  ">1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.90

  - node:    "2.4"
    progress:   "[14 23]"
    text:    "Tiene Ud. hipertensión arterial descontrolada? Tiene Ud. una enfermedad cardíaca o vascular? Sigue Ud. algún tratamiento cardiológico??"
    choices:
    - answer:  "Si"
      goto:    "2.5"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.5"
      color:   "is-info"
    - answer:  "No se"
      goto:    "2.5"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1

  - node:    "2.5"
    progress:   "[15 23]"
    text:    "Es Ud. diabético?"
    choices:
    - answer:  "Si"
      goto:    "2.6"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.6"
      color:   "is-info"

  - node:    "2.6"
    progress:   "[16 23]"
    text:    "Tiene Ud. cancer?"
    choices:
    - answer:  "Si"
      goto:    "2.7"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.7"
      color:   "is-info"

  - node:    "2.7"
    progress:   "[17 23]"
    text:    "Tiene Ud. una enfermedad respiratoria? Está Ud. en seguimiento por un neumonólogo?"
    choices:
    - answer:  "Si"
      goto:    "2.8"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.8"
      color:   "is-info"

  - node:    "2.8"
    progress:   "[18 23]"
    text:    "Tiene Ud. insuficiencia renal crónica que requiera diálisis?"
    choices:
    - answer:  "Si"
      goto:    "2.9"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.9"
      color:   "is-info"

  - node:    "2.9"
    progress:   "[19 23]"
    text:    "Tiene Ud. alguna enfermedad crónica del hígado?"
    choices:
    - answer:  "Si"
      goto:    "2.10"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.10"
      color:   "is-info"

  - node:    "2.10"
    progress:   "[20 23]"
    text:    "Esta Ud. embarazada?"
    choices:
    - answer:  "Si"
      goto:    "2.11"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.11"
      color:   "is-info"
    - answer:  "No aplica"
      goto:    "2.12"
      color:   "is-info"

  - node:    "2.11"
    progress:   "[21 23]"
    text:    "Tiene Ud. una enfermedad que disminuya sus defensas inmunológicas?"
    choices:
    - answer:  "Si"
      goto:    "2.12"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "2.12"
      color:   "is-info"
    - answer:  "No se"
      goto:    "2.12"
      color:   "is-info"

  - node:    "2.12"
    progress:   "[22 23]"
    text:    "Sigue Ud. algún tratamiento inmunosupresor?"
    help: "Sigue Ud. algún tratamiento que disminuya sus defensas? (ejemplo: corticoides, metotrexato, ciclosporina, tacrolimus, azatioprina, ciclofosfamida, entre otros)"
    choices:
    - answer:  "Si"
      goto:    "fin"
      color:   "is-info"
      score:
        facteurs-pronostiques:
          value: 1
    - answer:  "No"
      goto:    "fin"
      color:   "is-info"
    - answer:  "No se"
      goto:    "fin"
      color:   "is-info"

  - node: "fin-moins-de-15-ans"
    text: "Ud. tiene menos de 15 años"
    done: true

  - node: "fin"
    text: "Gracias por utilizar el algoritmo de orientación para COVID-19"
    help: "Algoritmo potencialmente modificable luego de estudios de casos y vigilancia científica."
    done: true
